#+TITLE: Ontology Visualization

* Example
#+BEGIN_SRC bash
  ./ontology_viz.py -o test.dot test.ttl -O ontology.ttl
  dot -Tpng -o test.png test.dot
#+END_SRC

- Use ~-o~ to indicate the path of output file
- Use ~-O~ to indicate the input ontology (Optional).
- Use ~-C~ to indicate the configuration file (Optional).
  - ~max_label_length~: config the max length of labels. If the text exceeds the length, exceeded part will be replaced with "...". Default value is ~0~.
  - ~blacklist~: config the predicate that you don't want to see in the graph.
  - ~class_inference_in_object~: config the predicate that can inference the object is a ~Class~, even if the class doesn't defined in the ontology.
- Classes defined in the ontology will be omitted in the output graph. This action can be switched with argument ~-V~.

* Requirements
In order to use this tool, you'll need to make sure you have [[https://github.com/RDFLib/rdflib][rdflib]] installed.

In order to convert =dot= into =png= or =svg= image, you will need [[https://www.graphviz.org][Graphviz]].
